baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"


[module]
  [[module.imports]]
    path = "github.com/meganii/amazon-json-data"
  [[module.mounts]]
    source = "data/amazon"
    target = "data/amazon"
